### PR TITLE
GCloud Assessment API Endpoints

### PR DESCRIPTION
**Pull request by NToppingCCS**
### JIRA link (if applicable) ###
https://crowncommercialservice.atlassian.net/browse/SCAT-6315

### Change description ###
Additions of 4 new endpoints for GCloud Assessments, and alteration of two existing non-GCloud assessment endpoints to encompass both types of assessment.

### Does this PR introduce a breaking change?

Not clear what this means - it will be a breaking change without the associated database changes going in as a separate PR.

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### CODE REVIEW

**Comment by NToppingCCS** [comment]
Trying to look into why Travis is struggling with this.  Could it possibly be because it's obviously generating classes from the database, and because the database changes have only currently been applied on my local machine it's therefore not able to generate all the dependencies it needs?

Would any reviewer have thoughts?  Has this been observed before when database changes have been made?

**Comment by NToppingCCS** [comment]
> > Trying to look into why Travis is struggling with this. Could it possibly be because it's obviously generating classes from the database, and because the database changes have only currently been applied on my local machine it's therefore not able to generate all the dependencies it needs?
> > Would any reviewer have thoughts? Has this been observed before when database changes have been made?
> 
> Is there any db related changes which effect the existing code. If yes than we review DB first and execute those DB changes in SBX2 and than need to rebuild this with updated code

Actually, yes thinking about it.  There's a couple of new tables but also a new field added to an existing one which will affect agreements.

PR for that is here: https://github.com/Crown-Commercial-Service/ccs-scale-db-scripts/pull/163

**Review by RajaKsv — CHANGES_REQUESTED** [review]
1. The entity classes are in the repo package,  it should be moved under - model/entity/(ca) package. 
2. I can see new methods are added in AssessmentsController and AssessmentService.  If possible could you move this to different file - GcloudAssessmentsController, GcloudAssessmentService.  Otherwise we would need to deal with merge conflict since both the teams would use the file.

The build is failing - more details - https://app.travis-ci.com/github/Crown-Commercial-Service/ccs-scale-cat-service/builds/254970657

**Comment by NToppingCCS** [comment]
No problem @RajaKsv - requested changes now made.  Sorry about the Entity one - must have not paid attention to where I was creating that last one!

Now that the database changes have been made, if the build still fails I'll investigate.

**Comment by RajaKsv** [comment]
Add the below attributes in  ProcurementEventServiceTest and RetryableTendersDBDelegateTest classes.  this will pass the build system.

Also, update the branch with latest changes from develop branch and we can merge the  PR. - Please run mvn test  and make sure the build passes in local system.

@MockBean
  private GCloudAssessmentRepo gCloudAssessmentRepo;
  @MockBean
  private GCloudAssessmentResultRepo gCloudAssessmentResultRepo;

**Comment by NToppingCCS** [comment]
Hi @RajaKsv - this should be good now I think :)

**Review by RajaKsv — APPROVED** [review]

**Pull request merged**
