### PR TITLE
Feature/scat 7580 jagger users

### PR DESCRIPTION
**Pull request by venkibric**
### JIRA link (if applicable) ###

https://crowncommercialservice.atlassian.net/browse/SCAT-7580

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

### CODE REVIEW

**Comment by NToppingCCS** [comment]
@venkibric - is this still needed?  The PR has been waiting for 4 months.

Do we need to merge it, or close it?

**Comment by venkibric** [comment]
> 

Yes Nathan. We need this. This should be merge but not now

**Comment by NToppingCCS** [comment]
No probs, thanks @venkibric - I'll leave it be for now then :)

**Comment by NToppingCCS** [comment]
Hi @venkibric 

Following on from your last comment on this one, is it STILL needed and if so can you detail for me when it will be needed and when it should be merged?

Thanks.

**Comment by NToppingCCS** [comment]
Been open 9 months, Brickenden could not provide support for what this was for or why it was still needed.  Therefore, closing.

**Pull request closed without merging**
